from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

import pytest

from repo2rlenv.curation.artifacts import digest_task, sanitize_generated_python_caches
from repo2rlenv.curation.verifier_review import VerifierInputError, _snapshot


def write(path: Path, content: bytes = b"pass\n") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return path


def cache(task: Path, name: str = "tests/__pycache__/test_contract.cpython-312.pyc") -> Path:
    return write(task / name, b"\xa7\r\r\n\x00\xffgenerated bytecode")


@pytest.mark.parametrize("folder", ["tests", "solution"])
@pytest.mark.parametrize(
    "relative,source",
    [
        ("__pycache__/helper.cpython-312.pyc", "helper.py"),
        ("__pycache__/helper.cpython-312.opt-1.pyc", "helper.py"),
        ("helper.pyc", "helper.py"),
        ("helper.pyo", "helper.py"),
    ],
)
def test_source_backed_cache_manifest_and_idempotence(tmp_path, folder, relative, source):
    task = tmp_path / "task"
    source_path = write(task / folder / source, b"VALUE = 13\n")
    bytecode = cache(task, f"{folder}/{relative}")
    original = bytecode.read_bytes()
    manifest = sanitize_generated_python_caches(task)

    assert manifest["policy_version"] == 1
    assert manifest["removed_files"] == [
        {
            "path": f"{folder}/{relative}",
            "source": f"{folder}/{source}",
            "sha256": hashlib.sha256(original).hexdigest(),
            "size_bytes": len(original),
        }
    ]
    assert manifest["removed_directories"] == (
        [f"{folder}/__pycache__"] if relative.startswith("__pycache__/") else []
    )
    assert json.loads(json.dumps(manifest)) == manifest
    assert not bytecode.exists()
    assert source_path.read_bytes() == b"VALUE = 13\n"
    digest = digest_task(task)
    assert sanitize_generated_python_caches(task) == {
        "policy_version": 1,
        "removed_files": [],
        "removed_directories": [],
    }
    assert digest_task(task) == digest


def test_preserves_other_files_and_cache_names_outside_evidence(tmp_path):
    task = tmp_path / "task"
    preserved = {
        "instruction.md": b"Keep this instruction exactly.\n",
        "tests/test_contract.py": b"def test_behavior():\n    assert True\n",
        "tests/fixture.bin": b"\x00\xfffixture",
        "tests/__pycache__/fixture.bin": b"\x00\xffnot bytecode",
        "tests/__pycache__/helper.py": b"VALUE = 3\n",
        "solution/solve.sh": b"#!/bin/sh\nexit 0\n",
        "environment/__pycache__/runtime.cpython-312.pyc": b"\x00\xffruntime",
        "elsewhere/other.pyc": b"\x00\xffother",
        "root.pyo": b"\x00\xffroot",
    }
    for name, content in preserved.items():
        write(task / name, content)
    bytecode = cache(task)

    manifest = sanitize_generated_python_caches(task)

    assert [row["path"] for row in manifest["removed_files"]] == [
        bytecode.relative_to(task).as_posix()
    ]
    assert manifest["removed_directories"] == []
    assert {name: (task / name).read_bytes() for name in preserved} == preserved


@pytest.mark.parametrize(
    "unsafe",
    [
        "tests/__pycache__/malicious.cpython-312.pyc",
        "solution/linked-directory",
        "environment/linked-file",
    ],
)
def test_rejects_symlinks_anywhere_before_removing_cache(tmp_path, unsafe):
    task = tmp_path / "task"
    write(task / "tests/test_contract.py")
    bytecode = cache(task)
    external = write(tmp_path / "outside/secret.pyc", b"external bytecode")
    link = task / unsafe
    link.parent.mkdir(parents=True, exist_ok=True)
    link.symlink_to(external.parent if unsafe.endswith("directory") else external)

    with pytest.raises(ValueError, match="Linked or non-regular"):
        sanitize_generated_python_caches(task)

    assert bytecode.exists()
    assert link.is_symlink()
    assert external.read_bytes() == b"external bytecode"


def test_rejects_linked_root_without_touching_target(tmp_path):
    real = tmp_path / "real-task"
    write(real / "tests/test_contract.py")
    bytecode = cache(real)
    linked = tmp_path / "linked-task"
    linked.symlink_to(real, target_is_directory=True)

    with pytest.raises(ValueError, match="Task root is not a regular directory"):
        sanitize_generated_python_caches(linked)

    assert bytecode.exists()


@pytest.mark.parametrize("kind", ["fifo", "hardlink"])
def test_rejects_nonregular_or_hardlinked_entries_before_removal(tmp_path, kind):
    task = tmp_path / "task"
    write(task / "tests/test_contract.py")
    bytecode = cache(task)
    unsafe = task / "environment/unsafe"
    unsafe.parent.mkdir()
    if kind == "fifo":
        os.mkfifo(unsafe)
    else:
        original = write(tmp_path / "outside", b"shared inode")
        os.link(original, unsafe)

    with pytest.raises(ValueError, match="Linked or non-regular"):
        sanitize_generated_python_caches(task)

    assert bytecode.exists()


@pytest.mark.parametrize(
    "orphan",
    [
        "solution/orphan.pyc",
        "solution/orphan.pyo",
        "tests/zorphan.pyc",
        "solution/__pycache__/orphan.cpython-312.pyc",
        "solution/__pycache__/malformed.pyc",
    ],
)
def test_orphan_or_malformed_bytecode_fails_before_any_removal(tmp_path, orphan):
    task = tmp_path / "task"
    write(task / "tests/test_contract.py")
    valid = cache(task)
    invalid = cache(task, orphan)

    with pytest.raises(ValueError, match=r"no regular source|Invalid generated Python cache"):
        sanitize_generated_python_caches(task)

    assert valid.exists()
    assert invalid.exists()


def test_sanitation_resolves_snapshot_cache_error_but_preserves_binary_fixture_error(tmp_path):
    task = tmp_path / "task"
    write(task / "instruction.md", b"Return the requested value.\n")
    write(task / "contract.json", b'{"requirements": []}\n')
    write(task / "tests/test_contract.py", b"def test_behavior():\n    assert True\n")
    bytecode = cache(task)
    with pytest.raises(VerifierInputError, match=r"non-UTF-8 evidence.*__pycache__"):
        _snapshot(task)

    sanitize_generated_python_caches(task)

    assert not bytecode.exists()
    assert _snapshot(task)["tests/test_contract.py"] == "def test_behavior():\n    assert True\n"
    binary = write(task / "tests/fixture.bin", b"\xff\x00fixture")
    assert sanitize_generated_python_caches(task)["removed_files"] == []
    assert binary.read_bytes() == b"\xff\x00fixture"
    with pytest.raises(VerifierInputError, match=r"non-UTF-8 evidence: tests/fixture\.bin"):
        _snapshot(task)
