"""OSS-Instruct-style coding tasks, anchored to a target repo + verified by execution.

For each emitted task:

  1. Sample a seed snippet from the target repo (Python file, 30-200 LOC)
  2. Ask the LLM for [Problem Description], [Test], [Solution] in one call
  3. Verify in the bootstrap container:
     - With ONLY the test file in place: `pytest <test_file>` must FAIL
       (otherwise the test doesn't actually exercise the oracle — trivial)
     - With BOTH the test and oracle: `pytest <test_file>` must PASS
       (otherwise the LLM's oracle is wrong)
  4. Emit Harbor task whose gold patch adds `task_module.py` (the oracle)
     and `test_<task_id>.py` (the verifier) at the repo root

Different from Magicoder's OSS-Instruct:
  - Seeds come from one specific repo (verified-solvable in THAT env)
  - Each task has an executable pytest verifier (not just text)
  - The oracle has to actually pass the test in the repo's Docker env

----------------------------------------------------------------------------
Acknowledgment
----------------------------------------------------------------------------
Inspired by:

  Magicoder: Empowering Code Generation with OSS-Instruct
  (Wei et al., ICML '24, arXiv:2312.02120)
  https://github.com/ise-uiuc/magicoder        (MIT)

The seed-snippet → LLM-instruction recipe is adapted from their
`data_synthesis/` pipeline. Section parsing and decontamination
heuristics follow their patterns but are reimplemented against
the Python stdlib (see _oss_instruct.py).

Released under Apache-2.0 along with the rest of Repo2RLEnv.
----------------------------------------------------------------------------
"""

from __future__ import annotations

import base64
import hashlib
import logging
import random
import shutil
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import ClassVar

from repo2rlenv.auth import resolve_github_token
from repo2rlenv.bootstrap.runner import _shallow_clone_at_ref
from repo2rlenv.bootstrap.spec import BootstrapResult, LanguageHint
from repo2rlenv.emitter.harbor import HarborTask, write_harbor_task
from repo2rlenv.llm import complete
from repo2rlenv.pipelines._oss_instruct import (
    PROMPT_SYSTEM,
    PROMPT_USER_TEMPLATE,
    ParsedTask,
    Seed,
    has_benchmark_overlap,
    list_source_files,
    parse_task_response,
    references_task_module,
    sample_seed,
)
from repo2rlenv.pipelines.base import PipelineResult
from repo2rlenv.pipelines.mutation_bugs import build_mutation_eval_script
from repo2rlenv.pipelines.pr_runtime import (
    _path_prelude_for_language,  # noqa: F401  (re-exported via mutation)
)
from repo2rlenv.spec.input import GenerationInput, PipelineName
from repo2rlenv.spec.options import CodeInstructOptions

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class _VerifyOutcome:
    accepted: bool = False
    reason: str = ""
    pre_log: str = ""
    post_log: str = ""


def _make_two_file_diff(*, task_module_code: str, test_code: str, test_filename: str) -> str:
    """Build a `git apply`-compatible diff that creates two NEW files at repo root.

    Both files are added (no deletes). The diff has standard `diff --git`
    + `new file mode` + index + `--- /dev/null` + `+++ b/<path>` headers
    for each file. Hunk: a single `@@ -0,0 +1,N @@` block.
    """

    def new_file_hunk(content: str, path: str) -> str:
        lines = content.splitlines()
        n = len(lines)
        header = (
            f"diff --git a/{path} b/{path}\n"
            f"new file mode 100644\n"
            f"index 0000000..0000001\n"
            f"--- /dev/null\n"
            f"+++ b/{path}\n"
            f"@@ -0,0 +1,{n} @@\n"
        )
        body = "".join(f"+{ln}\n" for ln in lines)
        if not content.endswith("\n"):
            body += "\\ No newline at end of file\n"
        return header + body

    return new_file_hunk(task_module_code, "task_module.py") + new_file_hunk(
        test_code, test_filename
    )


def build_code_instruct_dockerfile(bootstrap_image: str) -> str:
    """Per-task Dockerfile: FROM bootstrap + defensive git install. HEAD state.

    Unlike pr_runtime / mutation_bugs, code_instruct adds NEW files at
    test time (no patching needed at build time). Harbor's oracle agent
    applies solution/patch.diff which lands `task_module.py` + the test
    file at the repo root; then tests/test.sh runs pytest on the test.
    """
    return (
        f"# Auto-generated by Repo2RLEnv code_instruct\n"
        f"FROM {bootstrap_image}\n"
        f"WORKDIR /workspace\n"
        f"RUN command -v git >/dev/null 2>&1 || \\\n"
        f"    (apt-get update && apt-get install -y --no-install-recommends git \\\n"
        f"     && rm -rf /var/lib/apt/lists/*) || \\\n"
        f"    apk add --no-cache git || true\n"
        f"RUN git config --global --add safe.directory /workspace\n"
    )


class CodeInstructPipeline:
    """Repo-anchored OSS-Instruct with executable verifiers."""

    name: ClassVar[PipelineName] = PipelineName.CODE_INSTRUCT
    requires_bootstrap: ClassVar[bool] = True
    supported_languages: ClassVar[frozenset[LanguageHint] | None] = frozenset({LanguageHint.PYTHON})

    def __init__(
        self,
        input: GenerationInput,
        options: CodeInstructOptions,
        bootstrap: BootstrapResult | None = None,
    ):
        if bootstrap is None:
            raise RuntimeError(
                "code_instruct requires a BootstrapResult (set requires_bootstrap=True "
                "and let cmd_generate trigger it, or pass one explicitly)"
            )
        self.input = input
        self.options = options
        self.bootstrap = bootstrap
        self._progress_cb = None
        self._llm_cost_usd = 0.0

    def set_progress_callback(self, cb) -> None:
        self._progress_cb = cb

    def _emit_progress(self, name: str, outcome: str, reason: str = "") -> None:
        if self._progress_cb is not None:
            try:
                self._progress_cb(name=name, outcome=outcome, reason=reason)
            except Exception as exc:
                logger.debug("progress callback failed: %s", exc)

    # ----- run loop -----------------------------------------------------------

    def run(self, out_dir: Path) -> PipelineResult:
        out_dir.mkdir(parents=True, exist_ok=True)
        token = resolve_github_token(self.input.repo, self.input.auth)
        if self.input.repo.access == "private" and not token:
            raise RuntimeError(
                "private repo specified but no GitHub token resolved. "
                "Run `gh auth login` or set GITHUB_TOKEN."
            )

        owner, name = self.input.repo.owner_name
        owner_name = f"{owner}/{name}"
        rng = random.Random(self.options.seed) if self.options.seed is not None else random.Random()

        skip_reasons: dict[str, int] = {}
        emitted = 0
        candidates_seen = 0
        sandbox = None

        with tempfile.TemporaryDirectory(prefix="r2e-code-instruct-") as tmp:
            clone_dir = Path(tmp) / "repo"
            try:
                _shallow_clone_at_ref(
                    self.input.repo.url, self.input.repo.ref, token, clone_dir, depth=1
                )
            except Exception as exc:
                raise RuntimeError(f"failed to clone {self.input.repo.url}: {exc}") from exc

            source_files = list_source_files(
                clone_dir,
                file_glob=self.options.file_glob,
                exclude_glob=self.options.exclude_glob,
            )
            logger.info("code_instruct: %d candidate source files", len(source_files))

            try:
                if not self.options.skip_validation:
                    sandbox = self._start_sandbox()

                while emitted < self.options.limit:
                    if candidates_seen >= self.options.limit * 5:
                        # Avoid spinning forever on a repo that resists synthesis
                        logger.info(
                            "code_instruct: candidate budget exhausted (seen=%d, emitted=%d)",
                            candidates_seen,
                            emitted,
                        )
                        break
                    candidates_seen += 1
                    seed = sample_seed(
                        source_files,
                        clone_dir,
                        rng=rng,
                        min_loc=self.options.seed_min_loc,
                        max_loc=self.options.seed_max_loc,
                    )
                    if seed is None:
                        skip_reasons["no_seed"] = skip_reasons.get("no_seed", 0) + 1
                        continue
                    label = f"{owner_name}:{seed.relative_path}#{seed.start_line}-{seed.end_line}"

                    parsed = self._llm_synthesize(seed)
                    if parsed is None:
                        skip_reasons["llm_parse_failed"] = (
                            skip_reasons.get("llm_parse_failed", 0) + 1
                        )
                        self._emit_progress(label, "skip", "llm_parse_failed")
                        continue

                    # Decontamination
                    if not self.options.skip_decontamination:
                        joined = parsed.problem + "\n" + parsed.solution_code
                        if has_benchmark_overlap(joined):
                            skip_reasons["benchmark_overlap"] = (
                                skip_reasons.get("benchmark_overlap", 0) + 1
                            )
                            self._emit_progress(label, "skip", "benchmark_overlap")
                            continue

                    # Syntactic: test must reference task_module
                    if not references_task_module(parsed.test_code):
                        skip_reasons["test_does_not_use_task_module"] = (
                            skip_reasons.get("test_does_not_use_task_module", 0) + 1
                        )
                        self._emit_progress(label, "skip", "test_does_not_use_task_module")
                        continue

                    # Sandbox verification
                    test_filename = self._task_test_filename(seed, parsed)
                    if not self.options.skip_validation:
                        outcome = self._verify_task(sandbox, parsed, test_filename=test_filename)
                        if not outcome.accepted:
                            skip_reasons[outcome.reason] = skip_reasons.get(outcome.reason, 0) + 1
                            self._emit_progress(label, "skip", outcome.reason)
                            continue

                    # Emit
                    task = self._build_task(seed, parsed, test_filename=test_filename)
                    write_harbor_task(task, out_dir)
                    emitted += 1
                    logger.info("emitted task %s (seed=%s)", task.name, seed.relative_path)
                    self._emit_progress(task.name, "emit")
            finally:
                if sandbox is not None:
                    sandbox.cleanup()
                shutil.rmtree(clone_dir, ignore_errors=True)

        return PipelineResult(
            candidates=candidates_seen,
            emitted=emitted,
            skipped=sum(skip_reasons.values()),
            out_dir=out_dir,
            skip_reasons=skip_reasons,
        )

    # ----- LLM ---------------------------------------------------------------

    def _llm_synthesize(self, seed: Seed) -> ParsedTask | None:
        user = PROMPT_USER_TEMPLATE.format(
            path=seed.relative_path,
            start=seed.start_line,
            end=seed.end_line,
            snippet=seed.text,
        )
        try:
            resp = complete(
                self.input.llm,
                system=PROMPT_SYSTEM,
                user=user,
                max_tokens=self.options.max_llm_tokens,
                temperature=self.options.llm_temperature,
            )
        except Exception as exc:
            logger.warning("code_instruct LLM call failed: %s", exc)
            return None
        self._llm_cost_usd += resp.cost_usd
        return parse_task_response(resp.content)

    # ----- sandbox -----------------------------------------------------------

    def _start_sandbox(self):
        from repo2rlenv.bootstrap.docker import DockerSandbox

        marker = Path(tempfile.mkdtemp(prefix="r2e-code-instruct-"))
        (marker / ".keep").write_text("")
        return DockerSandbox.start(
            base_image=self.bootstrap.image_tag,
            repo_dir=marker,
            platform=self.input.bootstrap.platform,
        )

    def _verify_task(self, sandbox, parsed: ParsedTask, *, test_filename: str) -> _VerifyOutcome:
        """Two-stage verification.

        Stage A: write only the test file, run pytest on it → must NOT pass.
                 (Without the oracle module, the import fails or the
                  assertions fail. Either way, exit_code != 0.)
        Stage B: write both the test file AND task_module.py, re-run pytest →
                 must pass (exit_code == 0).
        """
        enc_test = base64.b64encode(parsed.test_code.encode("utf-8")).decode("ascii")
        enc_solution = base64.b64encode(parsed.solution_code.encode("utf-8")).decode("ascii")

        # Stage A — test only, no oracle
        script_a = (
            "set -uxo pipefail\n"
            "cd /workspace\n"
            "git config --global --add safe.directory /workspace\n"
            "git reset --hard HEAD\n"
            "git clean -fdx -e .venv -e venv -e __pycache__ || true\n"
            "rm -f task_module.py task_module.pyc || true\n"
            f"echo {enc_test} | base64 -d > {test_filename}\n"
            ": 'START_TEST_OUTPUT'\n"
            f"python -m pytest {test_filename} -v --no-header || true\n"
            ": 'END_TEST_OUTPUT'\n"
        )
        a = sandbox.exec(script_a, timeout=self.options.validation_timeout_sec)
        pre_log = a.truncated(max_chars=4000)
        # We re-check exit code by inspecting the log — pytest returns non-zero
        # on collection error or test failure. The wrapper command uses `|| true`
        # so the sandbox call always succeeds; we look for the "passed" summary
        # to decide.
        pre_passed = _all_tests_passed(pre_log)
        if self.options.require_test_fails_without_oracle and pre_passed:
            return _VerifyOutcome(
                accepted=False, reason="test_passes_without_oracle", pre_log=pre_log
            )

        # Stage B — oracle in place
        script_b = (
            "set -uxo pipefail\n"
            "cd /workspace\n"
            f"echo {enc_solution} | base64 -d > task_module.py\n"
            ": 'START_TEST_OUTPUT'\n"
            f"python -m pytest {test_filename} -v --no-header\n"
            ": 'END_TEST_OUTPUT'\n"
            # Restore HEAD state on exit
            f"rm -f task_module.py {test_filename}\n"
        )
        b = sandbox.exec(script_b, timeout=self.options.validation_timeout_sec)
        post_log = b.truncated(max_chars=4000)
        post_passed = b.ok and _all_tests_passed(post_log)
        if self.options.require_test_passes_with_oracle and not post_passed:
            return _VerifyOutcome(
                accepted=False,
                reason="oracle_does_not_satisfy_test",
                pre_log=pre_log,
                post_log=post_log,
            )

        return _VerifyOutcome(accepted=True, pre_log=pre_log, post_log=post_log)

    # ----- task builder -------------------------------------------------------

    def _task_test_filename(self, seed: Seed, parsed: ParsedTask) -> str:
        """Content-derived filename — pytest discovers it by `test_*.py` glob."""
        h = hashlib.sha256()
        h.update(seed.relative_path.encode())
        h.update(b"\0")
        h.update(str(seed.start_line).encode())
        h.update(b"\0")
        h.update(parsed.problem.encode())
        return f"test_r2e_{h.hexdigest()[:10]}.py"

    def _build_task(self, seed: Seed, parsed: ParsedTask, *, test_filename: str) -> HarborTask:
        owner, name = self.input.repo.owner_name
        h = hashlib.sha256()
        h.update(seed.relative_path.encode())
        h.update(b"\0")
        h.update(str(seed.start_line).encode())
        h.update(b"\0")
        h.update(parsed.problem.encode())
        task_id = f"{owner}__{name}-cinst-{h.hexdigest()[:8]}"

        gold_diff = _make_two_file_diff(
            task_module_code=parsed.solution_code,
            test_code=parsed.test_code,
            test_filename=test_filename,
        )

        # The verifier runs the synthesized test file specifically (NOT the
        # bootstrap's recorded test_cmds — those are for the original suite).
        eval_script = build_mutation_eval_script(
            [f"python -m pytest {test_filename} -v --no-header"],
            language=self.bootstrap.language.value,
        )
        image_ref = (
            self.bootstrap.image_digest
            if self.bootstrap.pushed_to_registry
            else self.bootstrap.image_tag
        )
        dockerfile = build_code_instruct_dockerfile(image_ref)

        repo2env = {
            "pipeline": "code_instruct",
            "pipeline_version": "0.6.0",
            "repo": f"{owner}/{name}",
            "ref": self.input.repo.ref,
            "reference": (
                f"https://github.com/{owner}/{name}/blob/{self.input.repo.ref}/"
                f"{seed.relative_path}#L{seed.start_line}-L{seed.end_line}"
            ),
            "source_access": self.input.repo.access,
            "built_at": datetime.now(UTC).isoformat(),
            "synthesis_llm": self.input.llm.qualified_name,
            "reward_kinds": ["test_execution"],
            "code_instruct": {
                "seed_path": seed.relative_path,
                "seed_start_line": seed.start_line,
                "seed_end_line": seed.end_line,
                "test_filename": test_filename,
                "bootstrap_image": self.bootstrap.image_digest,
                "llm_cost_usd": round(self._llm_cost_usd, 6),
            },
        }

        return HarborTask(
            name=task_id,
            org=self.input.output.org,
            description=parsed.problem.split("\n", 1)[0][:120],
            instruction=parsed.problem,
            oracle_diff=gold_diff,
            repo2env=repo2env,
            difficulty="medium",
            category="feature",
            keywords=[name, "code_instruct"],
            environment_dockerfile=dockerfile,
            test_script=eval_script,
        )


def _all_tests_passed(log: str) -> bool:
    """Heuristic: pytest summary line ends with `N passed` and no `failed`/`error`."""
    import re as _re

    lower = log.lower()
    if "error" in lower and "collected 0 items" in lower:
        return False
    # `0 failed` is fine; anything else is a failure
    if "failed" in lower and _re.search(r"\b[1-9]\d*\s+failed\b", lower):
        return False
    # A successful pytest run has a summary like `=== N passed in 0.12s ===`
    return bool(_re.search(r"\b[1-9]\d*\s+passed\b", lower))
