"""HF Hub push/pull for Repo2RLEnv datasets.

Generates a Harbor-compatible registry.json at the dataset root pointing at
the HF dataset's git URL + commit SHA, plus a friendly README dataset card.
Anyone can then `harbor download <task> --registry-url <hf-resolve-url>` to
pull tasks; this is verified to round-trip through `harbor`'s standard
git-clone path.

----------------------------------------------------------------------------
Acknowledgment
----------------------------------------------------------------------------
The `registry.json` format used here is Harbor's legacy registry format,
documented at:

  Harbor Framework (Laude Institute / Terminal-Bench creators)
  https://github.com/harbor-framework/harbor    (Apache-2.0)

We chose this format because (a) Harbor's existing `download` CLI parses it
out of the box (we tested), (b) HF Hub datasets are git repos, so an HF
dataset can serve registry.json AND host the task git references — closing
the loop with zero Harbor patches. We do NOT depend on the harbor Python
package; this module uses only `huggingface_hub` and stdlib JSON.

Released under Apache-2.0.
----------------------------------------------------------------------------
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from repo2rlenv.auth import resolve_hf_token
from repo2rlenv.spec.input import AuthSpec

logger = logging.getLogger(__name__)


@dataclass(slots=True)
class PushResult:
    repo_id: str
    commit_sha: str
    registry_url: str
    task_count: int


@dataclass(slots=True)
class PullResult:
    repo_id: str
    local_dir: Path
    task_count: int
    snapshot_path: Path  # actual on-disk location after snapshot_download


def _build_registry_json(
    repo_id: str,
    commit_sha: str,
    dataset_name: str,
    description: str,
    task_dirs: list[str],
) -> list[dict[str, Any]]:
    """Harbor's legacy registry.json format — list of DatasetSpec rows."""
    git_url = f"https://huggingface.co/datasets/{repo_id}"
    return [
        {
            "name": dataset_name,
            "version": "1.0",
            "description": description,
            "tasks": [
                {
                    "name": Path(task).name,
                    "git_url": git_url,
                    "git_commit_id": commit_sha,
                    "path": f"tasks/{Path(task).name}",
                }
                for task in task_dirs
            ],
        }
    ]


def _build_dataset_card(
    repo_id: str,
    dataset_name: str,
    task_count: int,
    repo_source: str,
    pipeline: str,
    visibility: str,
) -> str:
    return f"""---
license: apache-2.0
language:
  - en
size_categories:
  - n<1K
tags:
  - reinforcement-learning
  - code
  - llm
  - swe-rl
  - harbor
---

# {dataset_name}

Generated by [Repo2RLEnv](https://github.com/adithya-s-k/Repo2RLEnv).

- **Source repo**: [`{repo_source}`](https://github.com/{repo_source})
- **Pipeline**: `{pipeline}`
- **Tasks**: {task_count}
- **Visibility**: {visibility}
- **Spec**: Harbor task format with `[metadata.repo2env]` extension

## Reward kinds

This dataset emits `diff_similarity` rewards. Each task ships an oracle diff at
`solution/patch.diff`. Score a candidate prediction with:

```python
from repo2rlenv.reward import calculate_diff_similarity_reward
reward, meta = calculate_diff_similarity_reward(oracle, prediction)
```

A reward of `1.0` means byte-equivalent diffs (after normalizing volatile
metadata like hunk headers and index lines).

## Use with Harbor

```bash
harbor download {dataset_name} \\
  --registry-url https://huggingface.co/datasets/{repo_id}/resolve/main/registry.json
```

## Layout

```
tasks/
└── <task-id>/
    ├── task.toml          # Harbor task with [metadata.repo2env]
    ├── instruction.md     # natural-language prompt
    └── solution/
        └── patch.diff     # oracle diff
```

This is a SWE-RL-style lite dataset: text-only, no Docker required at
generation time.
"""


def push_to_hub(
    local_dataset_dir: Path,
    repo_id: str,
    auth: AuthSpec,
    *,
    private: bool = False,
    pipeline: str = "pr_diff",
    repo_source: str = "",
    description: str = "",
    commit_message: str | None = None,
) -> PushResult:
    """Push a dataset directory to HF Hub. Returns the resulting registry URL."""
    from huggingface_hub import HfApi

    token = resolve_hf_token(auth)
    if not token:
        raise RuntimeError("no HF token resolved. Run `huggingface-cli login` or set HF_TOKEN.")

    api = HfApi(token=token)
    api.create_repo(repo_id, repo_type="dataset", private=private, exist_ok=True)

    # Layout we expect locally: <root>/<task-id>/...
    # We'll re-stage it as <root>/tasks/<task-id>/...
    staging = local_dataset_dir / ".r2e_staging"
    staging.mkdir(exist_ok=True)
    tasks_dir = staging / "tasks"
    tasks_dir.mkdir(exist_ok=True)

    task_names = []
    for child in sorted(local_dataset_dir.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if not (child / "task.toml").exists():
            continue
        target = tasks_dir / child.name
        if target.exists():
            import shutil

            shutil.rmtree(target)
        import shutil as _sh

        _sh.copytree(child, target)
        task_names.append(child.name)

    if not task_names:
        raise RuntimeError(f"no Harbor tasks found in {local_dataset_dir}")

    # Write README.md (dataset card)
    dataset_name = repo_id.split("/")[-1]
    (staging / "README.md").write_text(
        _build_dataset_card(
            repo_id=repo_id,
            dataset_name=dataset_name,
            task_count=len(task_names),
            repo_source=repo_source,
            pipeline=pipeline,
            visibility="private" if private else "public",
        ),
        encoding="utf-8",
    )

    # First upload — without registry.json (we need the commit SHA first)
    logger.info("uploading %d tasks to %s", len(task_names), repo_id)
    op = api.upload_folder(
        folder_path=str(staging),
        repo_id=repo_id,
        repo_type="dataset",
        commit_message=commit_message or f"Repo2RLEnv: add {len(task_names)} tasks",
    )
    commit_sha = (
        op.oid
        if hasattr(op, "oid")
        else api.list_repo_commits(repo_id, repo_type="dataset")[0].commit_id
    )

    # Now write registry.json that pins the commit SHA we just got
    registry = _build_registry_json(
        repo_id=repo_id,
        commit_sha=commit_sha,
        dataset_name=dataset_name,
        description=description or f"Repo2RLEnv {pipeline} from {repo_source}",
        task_dirs=task_names,
    )
    registry_path = staging / "registry.json"
    registry_path.write_text(json.dumps(registry, indent=2), encoding="utf-8")

    api.upload_file(
        path_or_fileobj=str(registry_path),
        path_in_repo="registry.json",
        repo_id=repo_id,
        repo_type="dataset",
        commit_message="Add registry.json pinned to previous commit",
    )

    # Cleanup staging
    import shutil

    shutil.rmtree(staging)

    registry_url = f"https://huggingface.co/datasets/{repo_id}/resolve/main/registry.json"
    return PushResult(
        repo_id=repo_id,
        commit_sha=commit_sha,
        registry_url=registry_url,
        task_count=len(task_names),
    )


def pull_from_hub(
    repo_id: str,
    local_dir: Path,
    auth: AuthSpec | None = None,
    *,
    task: str | None = None,
    force: bool = False,
) -> PullResult:
    """Pull a Repo2RLEnv-published dataset from HF Hub into a local directory.

    Reverses `push_to_hub`: the staged Hub layout has `tasks/<task-id>/...`,
    and we flatten that back to `<local_dir>/<task-id>/...` so the result is
    immediately consumable by `repo2rlenv validate` and `harbor run --path`.

    Args:
        repo_id: HF dataset id, e.g. "AdithyaSK/click-r2e".
        local_dir: where to materialize the flattened tasks.
        auth: optional AuthSpec; falls back to env-resolved HF token.
        task: if set, fetch only that single task subdir (faster, smaller).
        force: re-download even if a local snapshot already exists.

    Returns a PullResult with the count of task directories materialized.
    """
    from huggingface_hub import snapshot_download

    auth = auth or AuthSpec()
    token = resolve_hf_token(auth)
    # token is optional for public datasets; pass-through if present

    if force and local_dir.exists():
        import shutil

        shutil.rmtree(local_dir)
    local_dir.mkdir(parents=True, exist_ok=True)

    allow_patterns = None
    if task:
        # Match the task subdir + the registry/README so a single-task pull
        # still produces a coherent dataset directory.
        allow_patterns = [
            f"tasks/{task}/**",
            "registry.json",
            "README.md",
        ]

    snapshot = Path(
        snapshot_download(
            repo_id=repo_id,
            repo_type="dataset",
            token=token,
            local_dir=str(local_dir / ".r2e_snapshot"),
            allow_patterns=allow_patterns,
        )
    )

    # Flatten staged `tasks/<id>/` → `<local_dir>/<id>/`
    staged_tasks = snapshot / "tasks"
    if not staged_tasks.exists():
        raise RuntimeError(
            f"{repo_id} doesn't look like a Repo2RLEnv dataset "
            f"(no `tasks/` subdir under {snapshot})"
        )

    import shutil

    task_count = 0
    for child in sorted(staged_tasks.iterdir()):
        if not child.is_dir():
            continue
        if not (child / "task.toml").exists():
            continue
        target = local_dir / child.name
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(child, target)
        task_count += 1

    # Also surface the registry.json + README.md at the dataset root so the
    # local layout matches what `push_to_hub` originally staged.
    for top in ("registry.json", "README.md"):
        src = snapshot / top
        if src.exists():
            shutil.copyfile(src, local_dir / top)

    # Clean up the snapshot scratch dir
    shutil.rmtree(snapshot, ignore_errors=True)

    if task_count == 0:
        raise RuntimeError(
            f"no Harbor tasks materialized from {repo_id} into {local_dir}"
            + (f" (filter: task={task!r})" if task else "")
        )

    return PullResult(
        repo_id=repo_id,
        local_dir=local_dir,
        task_count=task_count,
        snapshot_path=local_dir,
    )
